apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook
webhooks:
  - name: example.webhook.com
    clientConfig:
      service:
        name: example-mutating-webhook-svc
        namespace: crd
        path: /mutate
        port: 8443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lVUUlhTFQwb3IxbjlDaFplMHlmYTNyV1dDUmlNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2taWGhoYlhCc1pTMXRkWFJoZEdsdVp5MTNaV0pvYjI5ckxYTjJZeTVqY21RdQpjM1pqTUNBWERUSXpNVEV5T0RFek16WXhOVm9ZRHpJeU9UY3dPVEV4TVRNek5qRTFXakF2TVMwd0t3WURWUVFECkRDUmxlR0Z0Y0d4bExXMTFkR0YwYVc1bkxYZGxZbWh2YjJzdGMzWmpMbU55WkM1emRtTXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGdYU0dFdlc1QlhMWnZxVlZMWDFLTjczRzJNQ0MvQjVqKwpmOVhNckNnVUpWZW1Rd0dmaFZEbUh1SHZHSkxkQ3NLbGlzeFZlWU0vOUVtU1pqREdEeGdUZnVQdnJBL29TK2ZGCjBCcnptS3JNRG9BWTZtUHRDTnlLQnpkekxSTVh4c0JmdHFjVVE3eHZxbENxZ1VVSllYeDdCTVRFWFpSendvdXIKTzNFZUVkMlZvbFBpblljK3Vzc1I1Q3VTL0pPZWJXcUhJU0U5dGx5ZmdsQ0NhV2Q0RHZES3JTa0xoZllvVVE3TwpPcnhGMHFldnRsN2w2akwyOC9GeXpvcUVwcWc0RVdTZ01lYlQ5b1hYdHh6d3hBdGNzN2h3ZkVSZk9UVW1ocWNjClVkOE9qT3JsTXRSS28zcGRtUEpITTZTb2l4YkttTm1EZHo4RHo3Qk9TQ0U0dVhKb2Rhc1hBZ01CQUFHak16QXgKTUM4R0ExVWRFUVFvTUNhQ0pHVjRZVzF3YkdVdGJYVjBZWFJwYm1jdGQyVmlhRzl2YXkxemRtTXVZM0prTG5OMgpZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRGlHNUZBRXNaZU5sU2doem9iVUo0WFNONzVZZmJhK1NWSTVGCng3V05VeWpjeXo2aU5LTU9jVjlCMjBpK1hudzl4U0lmNkFtNEpaUWE4ZkloSFZ5ZXpTYTFyeTRmYi9EcTYxdE4KR1M2LzVNK3VzcTVKOHhXUnpKZXg2QlE5WjMxb1ZkZ2dLR0J1Ri9vWkVHNFNTaFVETE92bVQwaVBEKzVCUmpWWAp0TThSMDhvRC9VazZJblBRQVRrOTBTMC9HUlMzTmgwQmg3cy8yQzlEVk9KcENKV3M1a0FURE1SN1ZPYU5WSVJkCm8wR25DZHhSd2JEZkVWNmI2UTNjUkFzQkc2aEIwNjNYQ0g1b01CVEJycnd2bmV4cmw4UnhPcTA0U2dYb0dTYlIKNVVlbmhOSC9JdHBnYTdmZ0h5UkIwT2c2eThQakdMMXJ5NVE2anBkdXJ2cXFEWS9lNUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    # objectSelector:
    #   matchLabels:
    #     project: go-zero
    namespaceSelector:
      matchLabels:
        name: "go"
